default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: wolo
  port: 5432

development:
  <<: *default
  database: real_estate_app_development

test:
  <<: *default
  database: real_estate_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>  # Use Render's DATABASE_URL environment variable
